basePath: /
definitions:
  main.album:
    properties:
      artist:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample Gin server for managing record albums.
  title: Blue Train Record API
  version: "1.0"
paths:
  /albums:
    get:
      description: Responds with the list of all albums as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.album'
            type: array
      summary: Get all albums
    post:
      consumes:
      - application/json
      description: Takes a JSON body and adds it to the albums list.
      parameters:
      - description: Add album
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/main.album'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.album'
      summary: Add an album
  /albums/{id}:
    get:
      description: Returns a single album by its ID.
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.album'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get album by ID
swagger: "2.0"
